name: Cross-Compile

on:
  workflow_run:
    workflows:
      - "Versioning and Release"
    types:
      - completed
  workflow_dispatch:

jobs:
  cross_compile:
    if: (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Cross-compile for multiple architectures
      run: |
        echo "Building for target: ${{ matrix.target }}"
        cross build --target ${{ matrix.target }} --release || exit 1
      env:
        TARGET: ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rustgpt-discord-${{ matrix.target }}
        path: ./target/${{ matrix.target }}/release/rustgpt-discord${{ (matrix.target == 'x86_64-pc-windows-gnu') && '.exe' || '' }}
